-- MySQL Script generated by MySQL Workbench
-- mié 17 abr 2019 17:56:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Aquabid
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Aquabid` ;

-- -----------------------------------------------------
-- Schema Aquabid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aquabid` DEFAULT CHARACTER SET latin1 ;
USE `Aquabid` ;

-- -----------------------------------------------------
-- Table `Aquabid`.`Subasta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aquabid`.`Subasta` ;

CREATE TABLE IF NOT EXISTS `Aquabid`.`Subasta` (
  `ID_Subasta` INT(11) NOT NULL AUTO_INCREMENT,
  `realizada` TINYINT(1) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`ID_Subasta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Aquabid`.`Lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aquabid`.`Lote` ;

CREATE TABLE IF NOT EXISTS `Aquabid`.`Lote` (
  `ID_Lote` INT(11) NOT NULL AUTO_INCREMENT,
  `precio_salida` FLOAT NOT NULL,
  `precio_minimo` FLOAT NOT NULL,
  `Subasta_ID_Subasta` INT(11) NULL,
  PRIMARY KEY (`ID_Lote`),
  INDEX `fk_Lote_Subasta1_idx` (`Subasta_ID_Subasta` ASC),
  CONSTRAINT `fk_Lote_Subasta1`
    FOREIGN KEY (`Subasta_ID_Subasta`)
    REFERENCES `Aquabid`.`Subasta` (`ID_Subasta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Aquabid`.`Supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aquabid`.`Supervisor` ;

CREATE TABLE IF NOT EXISTS `Aquabid`.`Supervisor` (
  `ID_S` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `apellidos` VARCHAR(120) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `contrasenia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID_S`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Aquabid`.`Captura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aquabid`.`Captura` ;

CREATE TABLE IF NOT EXISTS `Aquabid`.`Captura` (
  `ID_P` INT(11) NOT NULL AUTO_INCREMENT,
  `barco` VARCHAR(120) NOT NULL,
  `zona_captura` VARCHAR(120) NOT NULL,
  `producto` VARCHAR(120) NOT NULL,
  `peso` INT(11) NOT NULL,
  `tamaño` INT(11) NOT NULL,
  `imagen` MEDIUMBLOB NOT NULL,
  `Lote_ID_Lote` INT(11) NULL,
  `Supervisor_ID_S` INT(11) NULL,
  PRIMARY KEY (`ID_P`),
  INDEX `fk_Captura_Lote1_idx` (`Lote_ID_Lote` ASC),
  INDEX `fk_Captura_Supervisor1_idx` (`Supervisor_ID_S` ASC),
  CONSTRAINT `fk_Captura_Lote1`
    FOREIGN KEY (`Lote_ID_Lote`)
    REFERENCES `Aquabid`.`Lote` (`ID_Lote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Captura_Supervisor1`
    FOREIGN KEY (`Supervisor_ID_S`)
    REFERENCES `Aquabid`.`Supervisor` (`ID_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Aquabid`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aquabid`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Aquabid`.`Clientes` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `usuario` VARCHAR(35) NOT NULL,
  `contrasenia` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nombreE` VARCHAR(120) NOT NULL,
  `direccionE` VARCHAR(120) NOT NULL,
  `telefonoE` VARCHAR(9) NOT NULL,
  `cip` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Aquabid`.`Clientes_has_Subasta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aquabid`.`Clientes_has_Subasta` ;

CREATE TABLE IF NOT EXISTS `Aquabid`.`Clientes_has_Subasta` (
  `Clientes_id_usuario` INT(11) NOT NULL,
  `Subasta_ID_Subasta` INT(11) NOT NULL,
  PRIMARY KEY (`Clientes_id_usuario`, `Subasta_ID_Subasta`),
  INDEX `fk_Clientes_has_Subasta_Subasta1_idx` (`Subasta_ID_Subasta` ASC),
  INDEX `fk_Clientes_has_Subasta_Clientes_idx` (`Clientes_id_usuario` ASC),
  CONSTRAINT `fk_Clientes_has_Subasta_Clientes`
    FOREIGN KEY (`Clientes_id_usuario`)
    REFERENCES `Aquabid`.`Clientes` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Subasta_Subasta1`
    FOREIGN KEY (`Subasta_ID_Subasta`)
    REFERENCES `Aquabid`.`Subasta` (`ID_Subasta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
